version: "3"

services:
  consul:
        image: "consul:1.15.4"
        container_name: consul
        ports:
        - "8500:8500"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
        - MYSQL_DATABASE=gorm
        - MYSQL_USER=gorm
        - MYSQL_PASSWORD=gorm
        - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
        - REDIS_PASSWORD=redis
        - REDIS_DATABASE=1
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
